storage_blkid: 0e856520-2315-4857-a5c7-14f326521e18

netplan_configuration:
    network:
      version: 2
      ethernets:
        enp3s0:
          match:
            macaddress: "ec:22:80:eb:a7:25"
          set-name: "enp3s0"
          mtu: 1500
        enp4s0:
          match:
            macaddress: "2c:56:dc:94:ff:77"
          optional: true
          set-name: "enp4s0"
          mtu: 1500
        enp6s0:
          match:
            macaddress: "e8:cc:18:e8:40:6e"
          optional: true
          set-name: "enp6s0"
          mtu: 1500
      bridges:
        br0:
          interfaces: [ enp3s0 ]
          addresses:
          - "172.23.0.26/16"
        br-management:
          interfaces: [ enp3s0.400 ]
          addresses:
          - "172.24.0.10/16"
          nameservers:
            addresses:
            - 172.24.0.2
        br-public:
          interfaces: [ enp3s0.401 ]
          dhcp4: true
        br-private:
          interfaces: [ enp3s0.402 ]
          addresses:
          - "172.26.0.10/16"
        br-san:
          interfaces: [ enp3s0.403 ]
          addresses:
          - "172.27.0.10/16"
        br-internet:
          interfaces: [ enp3s0.404 ]
          mtu: 1230
          addresses:
          - "172.28.0.10/16"
      vlans:
        enp3s0.400:
          mtu: 1500
          id: 400
          link: "enp3s0"
        enp3s0.401:
          mtu: 1500
          id: 401
          link: "enp3s0"
        enp3s0.402:
          mtu: 1500
          id: 402
          link: "enp3s0"
        enp3s0.403:
          mtu: 1500
          id: 403
          link: "enp3s0"
        # internet
        enp3s0.404:
          mtu: 1230
          id: 404
          link: "enp3s0"
