netplan_configuration:
  network:
    version: 2
    ethernets:
      enp8s0:
        match:
          macaddress: "f4:6d:04:6f:fa:18"
        set-name: "enp8s0"
        mtu: 1500
    bridges:
      br0:
        interfaces: [ enp8s0 ]
        addresses:
        - "172.23.0.35/16"
      br-management:
        interfaces: [ enp8s0.400 ]
        mtu: 1230
        addresses:
        - "172.24.0.17/16"
        nameservers:
          addresses:
          - 172.24.0.2
      br-public:
        interfaces: [ enp8s0.401 ]
        dhcp4: true
      br-private:
        interfaces: [ enp8s0.402 ]
        addresses:
        - "172.26.0.17/16"
    vlans:
      enp8s0.400:
        mtu: 1500
        id: 400
        link: "enp8s0"
      enp8s0.401:
        mtu: 1500
        id: 401
        link: "enp8s0"
      enp8s0.402:
        mtu: 1500
        id: 402
        link: "enp8s0"
