netplan_configuration:
  network:
    version: 2
    ethernets:
      enp3s0:
        match:
          macaddress: "c4:a8:1d:7e:93:89"
        optional: true
        set-name: "enp3s0"
        mtu: 1500
      enp4s0:
        match:
          macaddress: "60:a4:4c:37:39:4a"
        set-name: "enp4s0"
        mtu: 1500
    bridges:
      br0:
        interfaces: [ enp4s0 ]
        addresses:
        - "172.23.0.36/16"
      br-management:
        interfaces: [ enp4s0.400 ]
        addresses:
        - "172.24.0.18/16"
        nameservers:
          addresses:
          - 172.24.0.2
      br-public:
        interfaces: [ enp4s0.401 ]
        dhcp4: true
      br-private:
        interfaces: [ enp4s0.402 ]
        addresses:
        - "172.26.0.18/16"
    vlans:
      enp4s0.400:
        mtu: 1500
        id: 400
        link: "enp4s0"
      enp4s0.401:
        mtu: 1500
        id: 401
        link: "enp4s0"
      enp4s0.402:
        mtu: 1500
        id: 402
        link: "enp4s0"
