netplan_configuration:
  network:
    version: 2
    ethernets:
      enp3s0:
        match:
          macaddress: "38:2c:4a:be:37:bf"
        set-name: "enp3s0"
        mtu: 1500
    bridges:
      br0:
        interfaces: [ enp3s0 ]
        addresses:
        - "172.23.0.27/16"
      br-management:
        interfaces: [ enp3s0.400 ]
        mtu: 1230
        addresses:
        - "172.24.0.13/16"
        nameservers:
          addresses:
          - 172.24.0.2
      br-public:
        interfaces: [ enp3s0.401 ]
        dhcp4: true
      br-private:
        interfaces: [ enp3s0.402 ]
        addresses:
        - "172.26.0.13/16"
    vlans:
      enp3s0.400:
        mtu: 1500
        id: 400
        link: "enp3s0"
      enp3s0.401:
        mtu: 1500
        id: 401
        link: "enp3s0"
      enp3s0.402:
        mtu: 1500
        id: 402
        link: "enp3s0"
